name: Deploy Backend to Production

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy_backend_main.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          pull: true
          tags: ghcr.io/${{ github.actor }}/draftly-backend:latest 