name: Deploy to Production

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy_frontend_main.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Create .env file for frontend
        working-directory: frontend
        run: |
          echo "VITE_WS_SERVER_URL=wss://draftly-backend.ermolaev-frontend.ru" > .env
          echo "VITE_DEFAULT_ROOM_ID=room1" >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          pull: true
          tags: ghcr.io/${{ github.actor }}/draftly:latest

      - name: SSH and deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd $HOME/docker/draftly
            docker-compose -f docker-compose.frontend.yml pull   
            docker-compose -f docker-compose.frontend.yml up -d 