name: Verify build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/pull_request_frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: List files in frontend
        run: ls -l frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.check-build
          push: false
